### ISSUE TITLE
Fail to run on TensorFlow 

### ISSUE THREAD

**Issue by aikinogard** [hzy46/TensorFlow-Time-Series-Examples#1]
TensorFlow 1.3.0

`python train_lstm.py`

> Traceback (most recent call last):
>   File "train_lstm.py", line 173, in <module>
>     estimator = ts_estimators.TimeSeriesRegressor(
> AttributeError: 'module' object has no attribute 'TimeSeriesRegressor'

It seems TimeSeriesRegressor is in the master branch
in tensorflow/tensorflow/contrib/timeseries/python/timeseries/estimators.py

but the latest version 1.3.0 has it named _TimeSeriesRegressor

After I rename TimeSeriesRegressor to _TimeSeriesRegressor in train_lstm.py, I got this error

>   File "train_lstm.py", line 174, in <module>
>     model=_LSTMModel(num_features=1, num_units=128),
> TypeError: Can't instantiate abstract class _LSTMModel with abstract methods generate

Which version of TF do you use @hzy46 ?

**Comment by hzy46** [comment]
TF 1.3 is not enough. You should build from the latest code on TensorFlow's github repo. In TF 1.3, the _TimeSeriesRegressor is not fully implemented. Now it has become TimeSeriesRegressor. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/timeseries/python/timeseries/estimators.py

**Comment by aikinogard** [comment]
problem solved by using the newest build
