### ISSUE TITLE
使用LSTM预测单变量时间序列

### ISSUE THREAD

**Issue by fengjiqiang** [hzy46/TensorFlow-Time-Series-Examples#2]
from tensorflow.contrib.timeseries.python.timeseries.estimators import _TimeSeriesRegressor  前面应该加’_‘。

**Comment by hzy46** [comment]
same as https://github.com/hzy46/TensorFlow-Time-Series-Examples/issues/1

**Comment by wangye8899** [comment]
what？

**Comment by cmp1** [comment]
Im not sure I understand?
